package com.xtracker.android.objects;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JUMP.
 */
public class Jump {

    private Long jumpId;
    private Float airTime;
    private Long trackId;

    public Jump() {
    }

    public Jump(Long jumpId, Float airTime, Long trackId) {
        this.jumpId = jumpId;
        this.airTime = airTime;
        this.trackId = trackId;
    }

    public Long getJumpId() {
        return jumpId;
    }

    public void setJumpId(Long jumpId) {
        this.jumpId = jumpId;
    }

    public Float getAirTime() {
        return airTime;
    }

    public void setAirTime(Float airTime) {
        this.airTime = airTime;
    }

    public Long getTrackId() {
        return trackId;
    }

    public void setTrackId(Long trackId) {
        this.trackId = trackId;
    }

}
