package com.xtracker.android.objects;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POINT.
 */
public class Point {

    private Long pointId;
    private Double acceleration;
    private Float speed;
    private Double lat;
    private Double lon;
    private Double height;
    private Long trackId;

    public Point() {
    }

    public Point(Long pointId) {
        this.pointId = pointId;
    }

    public Point(Long pointId, Double acceleration, Float speed, Double lat, Double lon, Double height, Long trackId) {
        this.pointId = pointId;
        this.acceleration = acceleration;
        this.speed = speed;
        this.lat = lat;
        this.lon = lon;
        this.height = height;
        this.trackId = trackId;
    }

    public Long getPointId() {
        return pointId;
    }

    public void setPointId(Long pointId) {
        this.pointId = pointId;
    }

    public Double getAcceleration() {
        return acceleration;
    }

    public void setAcceleration(Double acceleration) {
        this.acceleration = acceleration;
    }

    public Float getSpeed() {
        return speed;
    }

    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    public Double getHeight() {
        return height;
    }

    public void setHeight(Double height) {
        this.height = height;
    }

    public Long getTrackId() {
        return trackId;
    }

    public void setTrackId(Long trackId) {
        this.trackId = trackId;
    }

}
